POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "any_value",
    "last_name": "any_value",
    "main_phone": { 
        "code": "main_code", 
        "phone": "main_phone" 
    },
    "other_phone": { 
        "code": "other_code", 
        "phone": "other_phone" 
    },
    "address": { 
        "state": "Piaui",
        "city": "Floriano",
        "street": "Av. Bucar Neto", 
        "number": "2150", 
        "district": "Bom Lugar", 
        "CEP": "64804430" 
    },
    "birth_date": "any_value"
}

###

GET http://localhost:3000/api

###

PUT http://localhost:3000/api/ee855e5f-869e-4577-91a1-7fbf5eeba696
Content-Type: application/json

{
    "first_name": "Francisco",
    "last_name": "Sousa",
    "main_phone": { 
        "code": "main_code", 
        "phone": "main_phone" 
    },
    "other_phone": { 
        "code": "other_code", 
        "phone": "other_phone" 
    },
    "address": { 
        "state": "Piaui",
        "city": "Floriano",
        "street": "Av. Bucar Neto", 
        "number": "2150", 
        "district": "Bom Lugar", 
        "CEP": "64804430" 
    },
    "birth_date": "any_value"
}

###

DELETE http://localhost:3000/api/ee855e5f-869e-4577-91a1-7fbf5eeba696